### ISSUE TITLE
Programmer Polyglot: Super Saiyan

### ISSUE THREAD

**Issue by azzamsa** [endymuhardin/endymuhardin.github.io#2]
Pagi, Pak Endi.

Bapak salah satu tokoh awal inspirasi saya di dunia programming sejak awal belajar coding di tahun 2015.
Perkenalan saya dengan blog bapak diawali oleh artikel yang ditulis oleh Ade Malasasa pada blog pribadinya.

Pada saat itu, hampir semua post pada blog bapak saya archive, khawatir post nya hilang.
Tetapi entah saat ini file nya sepertinya sudah sulit dicari.

Saya mencari lagi artikel yang dulu saya baca tentang Polyglot programming di tahun 2015. Saya ingat artikel itu menceritakan tentang bawha Super Saiyan tidak ekslusif lagi, semua orang sudah bisa bahkan anak kecil. Sayangnya, sudah saya coba banyak keyword di google dan di repository ini tetapi saya tidak menemukannya lagi. Apakah postnya memang sengaja dihapus, Pak?

Jika iya, bolehkan saya meminta arsip lama post tersebut?

Terima kasih banyak, Bapak.
Sehat selalu disana. 
Teringat dulu senang sekali melihat post dan video2 bapak. 
Terima kasih sudah menginsiprasi bangsa ini. 🇮🇩

**Comment by endymuhardin** [comment]
Itu bukan di blog. Tapi di channel youtube.
Ini linknya: https://youtu.be/mgf2ofYx8OE?si=mfsbDzz9ZOep4soU

**Comment by azzamsa** [comment]
Akhirnya.

Terima kasih banyak Pak 🙏🏻
